### PR TITLE
Ticket2111 instron stress rig

### PR DESCRIPTION
**Pull request by Tom-Willemsen**
### Description of work

Instron stress rig EPICS IOC.

### To test

https://github.com/ISISComputingGroup/IBEX/issues/2111

Ensure you also have the following changes when testing this:
https://github.com/ISISComputingGroup/ibex_gui/pull/505
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/14
https://github.com/ISISComputingGroup/EPICS-instron/pull/1
https://github.com/ISISComputingGroup/EPICS/pull/83
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/4

#### You will need to look at (at least) the following documents:
These are hosted on the sharepoint site under "Instron stress rig"
- "The spreadsheet" refers to `PVs.xlsx`
- "The reference manual" refers to `Stress Rig - GPIB.pdf`. Alternatively, there is a printed manual in the office.

#### Initialization
- [x] The initialization routine runs as documented on the spreadsheet. 

#### Reading from PVs
- [x] Reads from the device are done in a block
- [x] The watchdog is turned off before a block of reads (Interaction with device: `C904,0`)

#### Writing to PVs
- [x] For writes where it is needed, the device is put into computer control mode (`P909,1`) and taken out of computer control mode (`P909,0`) when it's finished

#### Rig commands
- [x] Stop button has PVs in place and sends a `C1,0` command to the rig. Note that the waveform PVs haven't been implemented yet so some of the records have TODOs on them. 
- [x] Panic stop behaves as expected.
- [x] Changing channels works as expected. (Caveat: channel commands are not yet in place, so cannot yet hide channels where `CHAN:TYPE:CHECK` is false).
- [x] Status bit 4 (Actuator active) is correctly parsed into `$(P)ACTUATOR:ON`
- [x] Status bits 9-12 are parsed into appropriate messages. See pages 5-42 and 5-43 of the reference manual. There is a mistake in the PDF version: `Power amplifier too hot` should report status code `0010` and not `1000`. This is consistent with both the labview driver and the printed manual.
- [x] You can set the type of movement using `$(P)MOVE:SP`. I've deviated slightly from the documents by combining several individual move commands into one PV with several possible values.
- [x] A utility PV called `$(P)MOVE:GO:SP` is provided, this stops and then starts movement.
- [x] If the rig reports a movement status of 2 or 5, then the movement is ended. Note that the movement status report from the rig is not the same as the movement type setpoint.
- [x] You can send arbitrary commands to the rig and get a response as expected

---

#### Code Review

- [x] Is the code of an acceptable quality?
- [x] Are the PVs named according to the [naming standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Naming).
- [x] Have suitable [disable records](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Disable-records) been added?
- [x] Have suitable [simulation records](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Record-Simulation) been added?
- [x] Have the [finishing touches](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches) been applied?
- [x] Is there an [emulator](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Emulating-Devices) for the device?
- [x] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [x] If an OPI has been modified, does it conform to the [style guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation)? There is a script called `check_opi_format.py` to help with this.

### Functional Tests

- [x] Do changes function as described? Add comments below that describe the tests performed.
- [x] Does the IOC respond correctly both in full and simulation mode, where it's possible to test both?
- [x] If there are multiple _0n IOCs, do they run correctly?
- [x] Ensure that the log files do not contain undefined macros, ie serach for `macLib: macro` full text is `macLib: macro XXXXX is undefined (expanding string XXXX)`

### Final steps

- [ ] Reviewer has updated the submodule in the main EPICS repo? See **Reviewing work for the subModules of EPICS** in the [Git workflow](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow) page for details.
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by AdrianPotter** [comment]
- [ ] Please add some IOC tests using the new framework
- [ ] Please double-check that there are no other `Interesting` PVs

**Comment by Tom-Willemsen** [comment]
IOC tests added here: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/4

**Comment by AdrianPotter** [comment]
When launching in RECSIM mode I get errors from a number of PVS:

```

**Comment by AdrianPotter** [comment]
The support module PR has already been merged but we've found a couple of things. Please change before this PR is closed:

- [ ] `setActuatorStatus` is no longer used
- [ ] `setCurrentControlChannel` should have remote mode set as in arbRW

**Comment by Tom-Willemsen** [comment]
Points 1 & 2 fixed on master of https://github.com/ISISComputingGroup/EPICS-instron as the PR was already merged.

Point 3: I think this acceptance criteria is now outdated after I changed the way the buttons work (previous review). I will modify the acceptance criteria to reflect this.

Point 4: No, I think the things you listed are the only expected behaviours (at least, as far as I can tell...)

Point 5: There is no way from the OPI/PVs, but I will add a back door function to the emulator to allow this

Point 6: I think `MOVE:GO:SP` is more appropriate here because it's a writable PV. I will update this acceptance criterion.

**Comment by AdrianPotter** [comment]
All great, thanks. Just one more tiny request. As discussed, please could `ACTUATOR:STAT` be a BI record that reports ON/OFF rather than 1/0. Given the device communicates as 1 for OFF and 0 for ON, we should be very clear what the PV means.

**Pull request merged**
