### PR TITLE
Ticket 2381: add records for showing valid frequencies

### PR DESCRIPTION
**Pull request by mattclarke**
### Description of work

https://github.com/ISISComputingGroup/IBEX/issues/2381

### To test

I have added PREC to the frequency fields so 16,67 Hz doesn't appear as 17 Hz in the OPI.
Confirm this using the IOC in simulation mode.
```
caput %MYPVPREFIX%MK2CHOPR_01:FREQ:SP 16.67
```

I have added a mbbo record that is used to set the FREQ:SP to "hard-coded" values only via the OPI. This requires the OPI changes also associated with this ticket.

### Acceptance criteria
The above tests work.

---

#### Code Review

- [x] Is the code of an acceptable quality?
- [x] Are the PVs named according to the [naming standards](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Naming).
- [x] Have suitable [disable records](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Disable-records) been added?
- [x] Have suitable [simulation records](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Record-Simulation) been added?
- [x] Have the [finishing touches](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches) been applied?
- [x] Is there an [emulator](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Emulating-Devices) for the device?
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev). If so, do they describe the changes appropriately?
- [ ] If an OPI has been modified, does it conform to the [style guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation)? There is a script called `check_opi_format.py` to help with this.

### Functional Tests

- [x] Do changes function as described? Add comments below that describe the tests performed.
- [x] Does the IOC respond correctly both in full and simulation mode, where it's possible to test both?
- [ ] If there are multiple _0n IOCs, do they run correctly?
- [ ] Ensure that the log files do not contain undefined macros, ie serach for `macLib: macro` full text is `macLib: macro XXXXX is undefined (expanding string XXXX)`

### Final steps

- [ ] Reviewer has updated the submodule in the main EPICS repo? See **Reviewing work for the subModules of EPICS** in the [Git workflow](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow) page for details.
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by DominicOram** [comment]
Works as described. Two queries:
* Should the choices field be flagged as interesting?
* The original ticket implies that the same should be done for the Mk3, did you forget? :wink:

**Comment by mattclarke** [comment]
The zeroth option is so when the IOC is started with the chopper stationary the SP combo comes up blank rather than, say, 5 Hz. I thought it would be less confusing for the user.

The choices shouldn't be a block I think. It is better to use the SP

**Comment by DominicOram** [comment]
That makes sense but it seems confusing that I can set a value of "" via the drop down and this does nothing. I'm happy to merge if there's no other solution though

**Comment by mattclarke** [comment]
Merge away.

**Pull request merged**
