### PR TITLE
Enable PVA and Kafka for liveview

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
### Description of work

Add kafka AD plugin to ISISDAE

### To test

See ISISComputingGroup/IBEX#5298

### Acceptance criteria

* data appears in nominated kafka topic
 
---

#### Code Review

- [ ] A copy of the manual has been placed on the shared drive
- [ ] Pertitent information has been stored in the [wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Specific-Device-IOC)
- [ ] Does the IOC conform to IBEX standards?
    - [PV naming](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PV-Naming).
    - [Disable records](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Disable-records)
    - [Record simulation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Record-Simulation)
    - [Finishing touches](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-Touches)
- [ ] If an OPI has been modified, does it conform to the [style guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation)?
- [ ] Do the IOC and support module conform to the new [build guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reducing-Build-Dependencies)
- [ ] Have the changes been recorded appropriately in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev)?
- [ ] Is the device's flow control setting correct? [For most devices flow control should be OFF](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Flow-control).

### Functional Tests

- IOC responds correctly in:
    - [ ] Devsim mode
    - [ ] Recsim mode
    - [ ] Real device, if available
- [ ] Supplementary IOCs (`..._0n` where `n>1`) run correctly
- [ ] Log files do not report undefined macros (serach for `macLib: macro` to find instances of `macLib: macro [macro name] is undefined...`

### Final steps

- [ ] Update the IOC submodule in the main EPICS repo. See [Git workflow](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow) page for details.
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

### CODE REVIEW

**Comment by DominicOram** [comment]
How do I get the ICP to produce uniform random events? My isisicp.properties is:
```
isisicp.usestoprundiscard = true

isisicp.epicsdb.use = true
isisicp.epicsdb.host = localhost
isisicp.epicsdb.singlelogfile = true

#isisicp.simulation.detcards.type = muon
#isisicp.simulation.detcards.crate0.number = 2

isisicp.simulation.detcards.type = neutron
isisicp.simulation.detcards.crate0.number = 4
#isisicp.simulation.detcards.crate0.number = 10
#isisicp.simulation.detcards.crate1.number = 9
#isisicp.simulation.detcards.crate2.number = 6

isisicp.simulation.detcards.shared = false
#isisicp.simulation.simulatedata = false
isisicp.simulation.simulatedata = true
isisicp.simulation.simulatespec0 = false
isisicp.simulation.simulatebin0 = false

isisicp.simulation.detcards.crate0.datadae.number = 0
```
And I have the first 64 spectra put into time regime 102 for event mode. But when I plot an 8x8 grid I get all zeroes.

**Comment by DominicOram** [comment]
Ok, sorry, I am getting random data, it's just awfully slow

**Comment by DominicOram** [comment]
Whilst data is getting into Kafka there are a number of issues with what is getting in:
* The timestamp of the kafka message is zero
* The dataType is set to `c_string`
* The data itself does not match the numbers I'm seeing in the liveview (I suspect this may be an issue with the datatype mismatch)

I think we need a bit more further investigation to work out whether this is an issue with AD_kafka or with the way we are loading it in.

**Comment by FreddieAkeroyd** [comment]
The c_string means you either have old autosave file (DATATYPE is autosaved) or there is a mismatch in the flatbuffer schema between sender and reader. Both areadetector and the flatbuffer had int64 and uint64 added whihc shited things along. Check DATATYPE is ok in the isisdae areadetctor, or just stop isisdae ioc and delete all autosave files

**Comment by DominicOram** [comment]
Thanks, that fixed the dataType but other two issues remain.

**Comment by FreddieAkeroyd** [comment]
The kafka plugin and dbLoadRecords use    RawImage1    rather than   ROI1, that was so if you did define a gui region of interest you still got all the original data in kafka, but might be worth putting kafka onto ROI1 and check that is not issue

**Comment by DominicOram** [comment]
After discussion with @matthew-d-jones I believe the issues are in `ad_to_kafka`. In the interests of getting this in for cycle I'm going to merge this and create tickets to investigate further on the `ad_to_kafka` side at a later date.

**Pull request merged**
